.. flat-table::
   :width: 100%
   :header-rows: 2

   * - :rspan:`1` 分類
     - :rspan:`1` 内容
     - :rspan:`1` ターゲット指定
     - :cspan:`6` `option-analysis`
     - :rspan:`1` 備考
   * - :analysis:`グラフ`
     - :analysis:`レポート`
     - | :analysis:`レート`
       | :analysis:`レーティング`
     - | :analysis:`対戦`
       | :analysis:`対戦結果`
     - :analysis:`統計`
     - :analysis:`素点`
     - :analysis:`比較`
   * - ランキング
     - `deliverables-ranking`
     - 任意
     - |:-:|
     - |:-:|
     - .. レーティング
     - .. 対戦
     - .. 統計
     - .. 素点
     - .. 比較
     - オプション指定なし
   * - :rspan:`1` レーティング
     - `deliverables-rating_table`
     - :rspan:`1` 任意
     - .. グラフ
     - |:-:|
     - |:/:|
     - |:-:|
     - |:-:|
     - |:-:|
     - |:-:|
     - レーティング表を表示
   * - `deliverables-rating_graph`
     - |:/:|
     - |:-:|
     - |:/:|
     - |:-:|
     - |:-:|
     - |:-:|
     - |:-:|
     - レーティング推移グラフを表示
   * - マトリクス
     - `deliverables-matchup_matrix`
     - 任意
     - |:-:|
     - |:-:|
     - .. レーティング
     - |:/:|
     - .. 統計
     - .. 素点
     - |:-:|
     - 対戦マトリクス表の表示
   * - ゲーム統計
     - `deliverables-game_statistics`
     - 任意
     - |:-:|
     - |:-:|
     - .. レーティング
     - |:-:|
     - |:/:|
     - .. 素点
     - |:-:|
     - ゲーム傾向の集計表を表示
   * - :rspan:`1` 素点分析
     - `deliverables-score_analysis`
     - :rspan:`1` 任意
     - .. グラフ
     - |:-:|
     - .. レーティング
     - |:-:|
     - |:-:|
     - |:/:|
     - |:-:|
     - 各順位の平均素点の偏差を表示
   * - `deliverables-score_chart`
     - |:/:|
     - |:-:|
     - .. レーティング
     - |:-:|
     - |:-:|
     - |:/:|
     - |:-:|
     - 平均素点 vs 平均順位の分散図を表示
   * - :rspan:`2` 成績詳細
     - `deliverables-results_report`
     - :rspan:`1` 単独
     - |:-:|
     - |:/:|
     - |:-:|
     - |:-:|
     - |:-:|
     - |:-:|
     - |:-:|
     - 成績レポート(PDF)を生成
   * - `deliverables-results_analysis`
     - |:/:|
     - .. レポート
     - |:-:|
     - |:-:|
     - |:-:|
     - |:-:|
     - |:-:|
     - 区間区切り集計グラフを表示
   * - `deliverables-results_list`
     - 任意
     - |:-:|
     - |:-:|
     - .. レーティング
     - .. 対戦
     - .. 統計
     - .. 素点
     - |:/:|
     - 成績詳細を並べて表示
..
