name: Deploy pdoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Generate documentation for sphinx
        run: |
          rm -rf ./temp_docs
          mkdir -p ./temp_docs/html/

          uv run sphinx-apidoc -f -o ./temp_docs/source/ . -d 3 --tocfile=index --module-first --separate
          uv run sphinx-build -M html ./temp_docs/source/ ./temp_docs/api/build --conf-dir ./docs/api/
          cp -r ./temp_docs/api/build/html ./temp_docs/html/api

          uv run sphinx-build -M html ./docs/user/source/ ./temp_docs/user/build --conf-dir ./docs/user/
          cp -r ./temp_docs/user/build/html ./temp_docs/html/user

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp_docs/html/
